# Generated by Django 3.2.3 on 2021-07-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20210713_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='images/pets'),
        ),
    ]
